
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Diganth Rai
 */
public class Collection_system extends javax.swing.JFrame {

    /**
     * Creates new form Collection_system
     */
    public Collection_system() {
        initComponents();
           table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     private void table_update()
            {
                int c;
        Connection dbconn = DBconnection.connectDB();
        try {
            PreparedStatement st;
            st= (PreparedStatement)dbconn.prepareStatement("select Cid,Eid,C_date,Total_collection,Salary,Fuel_price,Toll_fee,Expenditure,Balance,Bno from collection_system");   
            ResultSet rs=st.executeQuery();
            ResultSetMetaData Rss=rs.getMetaData();
            c=Rss.getColumnCount();
            
            DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
            Df.setRowCount(0);
//            adds the content of the table to the row
            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1;a<=c;a++)
                {
                    v2.add(rs.getString("Cid"));
                    v2.add(rs.getString("Eid"));
                    v2.add(rs.getString("Bno"));
                    v2.add(rs.getString("C_date"));
                    v2.add(rs.getString("Total_Collection"));
                    v2.add(rs.getString("Salary"));
                    v2.add(rs.getString("Fuel_price"));
                    v2.add(rs.getString("Toll_fee"));
                    v2.add(rs.getString("Expenditure"));
                    v2.add(rs.getString("Balance"));

                }
                Df.addRow(v2);
            }
        }catch (SQLException ex) {
            Logger.getLogger(Ologin.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        idlabel1 = new javax.swing.JLabel();
        tfid1 = new javax.swing.JTextField();
        tfb1 = new javax.swing.JTextField();
        idbusnum1 = new javax.swing.JLabel();
        datelabel1 = new javax.swing.JLabel();
        tfdate1 = new javax.swing.JTextField();
        tfcollection1 = new javax.swing.JTextField();
        totalcollectionlabel1 = new javax.swing.JLabel();
        sallabel1 = new javax.swing.JLabel();
        tfsal1 = new javax.swing.JTextField();
        tffuel1 = new javax.swing.JTextField();
        fuellabel1 = new javax.swing.JLabel();
        tolllabel1 = new javax.swing.JLabel();
        tftcost1 = new javax.swing.JTextField();
        tfexp1 = new javax.swing.JTextField();
        expendlabel1 = new javax.swing.JLabel();
        ballabel1 = new javax.swing.JLabel();
        tfbal1 = new javax.swing.JTextField();
        addbutton1 = new javax.swing.JButton();
        deletebutton1 = new javax.swing.JButton();
        editbutton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfcid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("COLLECTION SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(478, 478, 478))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));

        idlabel1.setText("Employee Id");

        idbusnum1.setText("Bus Number");

        datelabel1.setText("Date");

        totalcollectionlabel1.setText("Total Collection");

        sallabel1.setText("Salary");

        tfsal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsal1ActionPerformed(evt);
            }
        });

        fuellabel1.setText("Fuel Cost");

        tolllabel1.setText("Toll Cost");

        expendlabel1.setText("Total Expenditure");

        ballabel1.setText("Balance");

        addbutton1.setBackground(new java.awt.Color(255, 255, 255));
        addbutton1.setText("Add");
        addbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbutton1ActionPerformed(evt);
            }
        });

        deletebutton1.setBackground(new java.awt.Color(255, 255, 255));
        deletebutton1.setText("Delete");
        deletebutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebutton1ActionPerformed(evt);
            }
        });

        editbutton1.setBackground(new java.awt.Color(255, 255, 255));
        editbutton1.setText("Edit");
        editbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbutton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Collection Id");

        tfcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfcid))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addbutton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletebutton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editbutton1)))
                .addGap(45, 45, 45))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(datelabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(tfdate1))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(totalcollectionlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfcollection1))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(sallabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(tfsal1))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(fuellabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(tffuel1))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(expendlabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfexp1))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(tolllabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(tftcost1))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idbusnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfb1)
                                .addComponent(tfid1)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(ballabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(tfbal1)))
                    .addGap(43, 43, 43)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbutton1)
                    .addComponent(deletebutton1)
                    .addComponent(editbutton1))
                .addGap(39, 39, 39))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idlabel1))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idbusnum1))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(datelabel1))
                    .addGap(21, 21, 21)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfcollection1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalcollectionlabel1))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(tfsal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tffuel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fuellabel1))
                            .addGap(16, 16, 16)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tftcost1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tolllabel1))
                            .addGap(16, 16, 16)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfexp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(expendlabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfbal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ballabel1)))
                        .addComponent(sallabel1))
                    .addContainerGap(84, Short.MAX_VALUE)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Employee Id", "Bus No", "Date", "Total Collection", "Salary", "Fuel Cost", "Toll Cost", "Total Expenditure", "Balance"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfsal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsal1ActionPerformed

    private void addbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbutton1ActionPerformed
        String cid=tfcid.getText();
        String eid=tfid1.getText();
        String bno=tfb1.getText();
        String date=tfdate1.getText();
        String collection=tfcollection1.getText();
        String salary=tfsal1.getText();
        String fuel=tffuel1.getText();
        String toll=tftcost1.getText();
        String expenditure=tfexp1.getText();
        String balance=tfbal1.getText();
        String useridregex="Eid[0-9]+";
        String cidregex="[0-9]+";
        String bnoregex="[A-Z][A-Z][0-9][0-9][A-Z][A-Z][0-9][0-9][0-9][0-9]";
        String dateregex="^(202[2-9])[./-]([0]?[1-9]|[1][0-2])[./-]([0]?[1-9]|[1|2][0-9]|[3][0|1])$";




        if(cid.isEmpty() || eid.isEmpty() || date.isEmpty() || bno.isEmpty()|| date.isEmpty() || collection.isEmpty() || balance.isEmpty() || salary.isEmpty()|| fuel.isEmpty() || toll.isEmpty() || expenditure.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Fill proper details.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if(cid.length()<=5)
        {
            if(cid.matches(cidregex))
            {
                if(eid.length()<=5)
            {
                if(eid.matches(useridregex))
                {
                    if(bno.length()==10)
                    {
                
                    if(bno.matches(bnoregex))
                    {
            
                    if(date.matches(dateregex))
                    {
                        userinsert(cid,eid,date,collection,salary,fuel,toll,expenditure,balance,bno);
                    }
                    else{
                                JOptionPane.showMessageDialog(this, "DATE must be in the YYYY-MM-DD format", "Error", JOptionPane.ERROR_MESSAGE);    
                               }
                           }
                    else{
                                                        JOptionPane.showMessageDialog(this, "Invalid Number Plate format", "Error", JOptionPane.ERROR_MESSAGE);    

                    }
                        
                    }
                    else{
                                                                                JOptionPane.showMessageDialog(this, "Number plate length must be 10", "Error", JOptionPane.ERROR_MESSAGE);    
                        
                    }
                }
                    else
                    {
                         JOptionPane.showMessageDialog(this, "EMPLOYEE ID is not in the right format (Eg. Eid1)", "Error", JOptionPane.ERROR_MESSAGE);    

                    }
                    }
                else
                {
               JOptionPane.showMessageDialog(this, "EMPLOYEE ID length should not exceed 5", "Error", JOptionPane.ERROR_MESSAGE);    

                }
                    }
             else
                {
               JOptionPane.showMessageDialog(this, "COLLECTION ID must be in digit ", "Error", JOptionPane.ERROR_MESSAGE);    

                }
                    }
        else{
                   JOptionPane.showMessageDialog(this, "COLLECTION ID length should not exceed 5", "Error", JOptionPane.ERROR_MESSAGE);    
            
        }

    }//GEN-LAST:event_addbutton1ActionPerformed

    private void deletebutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebutton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
        int selectedIndex=jTable1.getSelectedRow();
        Connection dbconn = DBconnection.connectDB();
        try{
            //        String Eid=Integer.parseInt(Df.getValueAt(selectedIndex,0).toString());
            String cid=tfcid.getText();
            int dialogResult= JOptionPane.showConfirmDialog(null,"Do you want to delete the record","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION)
            {
                PreparedStatement st;
                st= (PreparedStatement)dbconn.prepareStatement("delete from collection_system where Cid = ?");
                st.setString(1,cid);
                st.executeUpdate();
                JOptionPane.showMessageDialog(this,"Deleted successfully");
                table_update(); 
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(Ologin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletebutton1ActionPerformed

    private void editbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbutton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
        int selectedIndex=jTable1.getSelectedRow();
        Connection dbconn = DBconnection.connectDB();

        try{
            //        String Eid=Integer.parseInt(Df.getValueAt(selectedIndex,0).toString());
            String cid=tfcid.getText();
            String eid=tfid1.getText();
            String bno=tfb1.getText();
            String date=tfdate1.getText();
            String collection=tfcollection1.getText();
            String salary=tfsal1.getText();
            String fuel=tffuel1.getText();
            String toll=tftcost1.getText();
            String expenditure=tfexp1.getText();
            String balance=tfbal1.getText();
            PreparedStatement st;
            st= (PreparedStatement)dbconn.prepareStatement("update collection_system set Eid=?,C_date=?,Total_collection=?,Salary=?,Fuel_price=?,Toll_fee=?,Expenditure=?,Balance=?,Bno=? where Cid=?");
            st.setString(1,eid);
            st.setString(2,date);
            st.setString(3,collection);
            st.setString(4,salary);
            st.setString(5,fuel);
            st.setString(6,toll);
            st.setString(7,expenditure);
            st.setString(8,balance);
            st.setString(9,bno);
            st.setString(10,cid);
            st.executeUpdate();
            JOptionPane.showMessageDialog(this,"Updated successfully");
            table_update();

            tfid1.setText("");
            tfb1.setText("");
            tfdate1.setText("");
            tfcollection1.setText("");
            tfsal1.setText("");
            tftcost1.setText("");
            tffuel1.setText("");
            tfexp1.setText("");
            tfbal1.setText("");
            tfcid.setText("");
            tfcid.requestFocus();
        }catch (SQLException ex) {
            Logger.getLogger(Ologin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editbutton1ActionPerformed

    private void tfcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcidActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
  DefaultTableModel Df=(DefaultTableModel)jTable1.getModel();
    int selectedIndex=jTable1.getSelectedRow();
//    insert the selected row to the text field
    tfcid.setText(Df.getValueAt(selectedIndex,0 ).toString());
        tfid1.setText(Df.getValueAt(selectedIndex,1 ).toString());

    tfb1.setText(Df.getValueAt(selectedIndex,2 ).toString());
    tfdate1.setText(Df.getValueAt(selectedIndex,3 ).toString());
    tfcollection1.setText(Df.getValueAt(selectedIndex,4 ).toString());
    tfsal1.setText(Df.getValueAt(selectedIndex,5 ).toString());
    tffuel1.setText(Df.getValueAt(selectedIndex,6 ).toString());
    tftcost1.setText(Df.getValueAt(selectedIndex,7 ).toString());
    tfexp1.setText(Df.getValueAt(selectedIndex,8 ).toString());
    tfbal1.setText(Df.getValueAt(selectedIndex,9 ).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here
        Ehome j=new Ehome();
        j.show();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Collection_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Collection_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Collection_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Collection_system.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Collection_system().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton addbutton1;
    private javax.swing.JLabel ballabel;
    private javax.swing.JLabel ballabel1;
    private javax.swing.JLabel datelabel;
    private javax.swing.JLabel datelabel1;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton deletebutton1;
    private javax.swing.JButton editbutton;
    private javax.swing.JButton editbutton1;
    private javax.swing.JLabel expendlabel;
    private javax.swing.JLabel expendlabel1;
    private javax.swing.JLabel fuellabel;
    private javax.swing.JLabel fuellabel1;
    private javax.swing.JLabel idbusnum;
    private javax.swing.JLabel idbusnum1;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel idlabel1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel sallabel;
    private javax.swing.JLabel sallabel1;
    private javax.swing.JTextField tfb;
    private javax.swing.JTextField tfb1;
    private javax.swing.JTextField tfbal;
    private javax.swing.JTextField tfbal1;
    private javax.swing.JTextField tfcid;
    private javax.swing.JTextField tfcollection;
    private javax.swing.JTextField tfcollection1;
    private javax.swing.JTextField tfdate;
    private javax.swing.JTextField tfdate1;
    private javax.swing.JTextField tfexp;
    private javax.swing.JTextField tfexp1;
    private javax.swing.JTextField tffuel;
    private javax.swing.JTextField tffuel1;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfid1;
    private javax.swing.JTextField tfsal;
    private javax.swing.JTextField tfsal1;
    private javax.swing.JTextField tftcost;
    private javax.swing.JTextField tftcost1;
    private javax.swing.JLabel tolllabel;
    private javax.swing.JLabel tolllabel1;
    private javax.swing.JLabel totalcollectionlabel;
    private javax.swing.JLabel totalcollectionlabel1;
    // End of variables declaration//GEN-END:variables

    private void userinsert(String cid, String eid, String date, String collection, String salary, String fuel, String toll, String expenditure, String balance, String bno) {
Connection dbconn = DBconnection.connectDB();
        try {
            PreparedStatement st;
            st= (PreparedStatement)dbconn.prepareStatement("insert into collection_system (Cid,Eid,C_date,Total_collection,Salary,Fuel_price,Toll_fee,Expenditure,Balance,Bno) values(?,?,?,?,?,?,?,?,?,?)"); 
            st.setString(1,cid);
            st.setString(2,eid);
            st.setString(3,date);
            st.setString(4,collection);
            st.setString(5,salary);
            st.setString(6,fuel);
            st.setString(7,toll);
            st.setString(8,expenditure);
            st.setString(9,balance);
            st.setString(10,bno);
            int res= st.executeUpdate();
            JOptionPane.showMessageDialog(this,"Inserted successfully");
//calling the table_update functions adds the table at once to the display
            table_update();
            tfcid.setText("");
            tfid1.setText("");
            tfb1.setText("");
            tfdate1.setText("");
            tfcollection1.setText("");
            tfsal1.setText("");
            tftcost1.setText("");
            tffuel1.setText("");
            tfexp1.setText("");
            tfbal1.setText("");            
            tfcid.requestFocus();                       
        }catch (SQLException ex) {
                          JOptionPane.showMessageDialog(this, ex, "Error", JOptionPane.ERROR_MESSAGE);    

            Logger.getLogger(Ologin.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
}