
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Diganth Rai
 */
public class elogin extends javax.swing.JFrame {

    /**
     * Creates new form elogin
     */
    public elogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        usernamelabel = new javax.swing.JLabel();
        passwordlabel = new javax.swing.JLabel();
        tfuserid = new javax.swing.JTextField();
        tfusername = new javax.swing.JTextField();
        loginbutton = new javax.swing.JButton();
        loginlabel = new javax.swing.JLabel();
        ftpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        registerlabel = new javax.swing.JLabel();
        useridlabelr = new javax.swing.JLabel();
        usernamelabelr = new javax.swing.JLabel();
        contactnumberlabelr = new javax.swing.JLabel();
        passwordlabelr = new javax.swing.JLabel();
        fpassword = new javax.swing.JPasswordField();
        tfownerid = new javax.swing.JTextField();
        fcontactnumber = new javax.swing.JTextField();
        fusername = new javax.swing.JTextField();
        fuserid = new javax.swing.JTextField();
        registerbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfrole = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfsal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfaddress = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        usernamelabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usernamelabel.setText("Username");

        passwordlabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordlabel.setText("Password");

        tfuserid.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tfuserid.setForeground(new java.awt.Color(153, 153, 153));
        tfuserid.setText("Eg. Eid1");
        tfuserid.setToolTipText("");
        tfuserid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfuseridFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfuseridFocusLost(evt);
            }
        });
        tfuserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuseridActionPerformed(evt);
            }
        });

        tfusername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        loginbutton.setBackground(new java.awt.Color(255, 204, 0));
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        loginlabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        loginlabel.setText("LOGIN TO START!");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Userid");

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(160, 15));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(15, 160));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ftpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(65, 65, 65))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfuserid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                        .addComponent(loginbutton)
                                        .addGap(75, 75, 75))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(loginlabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(loginlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfuserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamelabel)
                    .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordlabel)
                    .addComponent(ftpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loginbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 0));

        registerlabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        registerlabel.setText("ARE YOU A NEW USER?...");

        useridlabelr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        useridlabelr.setText("User Id");

        usernamelabelr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usernamelabelr.setText("Username");

        contactnumberlabelr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contactnumberlabelr.setText("Contact Number");

        passwordlabelr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordlabelr.setText("Password");

        fpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpasswordActionPerformed(evt);
            }
        });

        tfownerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfowneridActionPerformed(evt);
            }
        });

        fusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fusernameActionPerformed(evt);
            }
        });

        fuserid.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        fuserid.setForeground(new java.awt.Color(153, 153, 153));
        fuserid.setText("Eg. Eid1");
        fuserid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fuseridFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fuseridFocusLost(evt);
            }
        });

        registerbutton.setBackground(new java.awt.Color(255, 255, 255));
        registerbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerbutton.setText("Submit");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Owner Id");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Role");

        tfrole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfrole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Driver", "Conductor", "Cleaner" }));
        tfrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfroleActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Salary/month");

        tfsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsalActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Address");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordlabelr, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfownerid)
                            .addComponent(fpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                            .addComponent(usernamelabelr)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(contactnumberlabelr, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(useridlabelr, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fuserid, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(fcontactnumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fusername, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfrole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfsal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfaddress, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(registerlabel)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(registerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(registerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useridlabelr)
                    .addComponent(fuserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamelabelr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fcontactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactnumberlabelr))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tfaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfownerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordlabelr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfuseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuseridActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        String userid=tfuserid.getText();
        String username=tfusername.getText();
        String password=String.valueOf(ftpassword.getPassword());
        if(userid.isEmpty() || username.isEmpty() || password.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Username /Password should not be empty", "Error", JOptionPane.ERROR_MESSAGE);
        } else{
            userLogin(userid,username,password);
            //                    suserart the login process

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void tfroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfroleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfroleActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        // TODO add your handling code here:
        String userid=fuserid.getText();
        String username=fusername.getText();
        String contactnumber=fcontactnumber.getText();
        String address=tfaddress.getText();
        String role=(String)tfrole.getSelectedItem();
        String sal=tfsal.getText();
        String ownerid=tfownerid.getText();
        
        // Regex field
        String useridregex="Eid[0-9]+";
        String owneridregex="Oid[0-9]+";
        String passwordregex="^[A-Z][0-9 a-z]+[ @ # % & ! $ ]+$";
        String nameregex="^[A-Z][a-z]+";
        String phnregex="[0-9]+";

        String password=String.valueOf(fpassword.getPassword());
        if(userid.isEmpty() || username.isEmpty() || password.isEmpty() || contactnumber.isEmpty() || address.isEmpty() || role.isEmpty() || sal.isEmpty() || ownerid.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill proper details.", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
//      Userid
        if(userid.length()<=5)
        {
            if(userid.matches(useridregex))
            {
                System.out.println("success1");
                //Username
                if(username.length()<=30)
                    {
                        if(username.matches(nameregex))
                        {
                            System.out.println("success2");
                             //contact number
                             if(contactnumber.length()==10)
                                    {
                                        if(contactnumber.matches(phnregex))
                                        {
                                            System.out.println("success3");
                                            //ownerid
                                            if(ownerid.length()<=5)
                                            {
                                                if(ownerid.matches(owneridregex))
                                                {
                                                    System.out.println("success4");
                                         //password

                                            if(password.length()==10){
                                                if(password.matches(passwordregex))
                                                {
                                                   userRegister(userid,username,contactnumber,address,role,ownerid,password,sal);
//                                                    userRegister(userid,username,contactnumber, address,password);
                                                }
                                                else
                                                {
                                                 JOptionPane.showMessageDialog(this, "Begin PASSWORD with Uppercase, use lowercase,,digits and end with (@,#,$,%,&,!)", "Error", JOptionPane.ERROR_MESSAGE);        
                                                }
                                            }

                                            else{
                                                  JOptionPane.showMessageDialog(this, "PASSWORD length is not 10 ", "Error", JOptionPane.ERROR_MESSAGE);
                                            }                                       
                                        }
                                       else
                                        {
                                         JOptionPane.showMessageDialog(this, "OWNERID  not in the required form (eg.Oid1)", "Error", JOptionPane.ERROR_MESSAGE);        
                                        }
                                    }
                                    else
                                    {
                                         JOptionPane.showMessageDialog(this, "max ID length is 5 ", "Error", JOptionPane.ERROR_MESSAGE);
                                    }
                                }
                                else
                                        {
                                         JOptionPane.showMessageDialog(this, "Enter 10 digit CONTACT NUMBER", "Error", JOptionPane.ERROR_MESSAGE);        
                                        }
                                    }
                                    else
                                    {
                                         JOptionPane.showMessageDialog(this, "CONTACT NUMBER is not 10 ", "Error", JOptionPane.ERROR_MESSAGE);
                                    }    
                                }
                            else
                           {
                                JOptionPane.showMessageDialog(this, "Begin NAME with Uppercase followed by ONLY Lowercase", "Error", JOptionPane.ERROR_MESSAGE);        
                             }
                           }
                    else
                    {
                         JOptionPane.showMessageDialog(this, "Max NAME length is 30 ", "Error", JOptionPane.ERROR_MESSAGE);
                    }     
            }
            else
            {
             JOptionPane.showMessageDialog(this, "ID  not in the required form (eg.Eid1)", "Error", JOptionPane.ERROR_MESSAGE);        
            }
        }
        else
        {
             JOptionPane.showMessageDialog(this, "max ID length is 5 ", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
        
        

        
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void fusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fusernameActionPerformed

    private void tfowneridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfowneridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfowneridActionPerformed

    private void fpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fpasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        home j=new home();
        j.show();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsalActionPerformed

    private void fuseridFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fuseridFocusGained
        // TODO add your handling code here:
         if(fuserid.getText().equals("Eg. Eid1"))
        {
            fuserid.setText("");
            fuserid.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_fuseridFocusGained

    private void fuseridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fuseridFocusLost
        // TODO add your handling code here:
         if(fuserid.getText().equals(""))
        {
            fuserid.setText("Eg. Eid1");
            fuserid.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_fuseridFocusLost

    private void tfuseridFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfuseridFocusGained
        // TODO add your handling code here:
         if(tfuserid.getText().equals("Eg. Eid1"))
        {
            tfuserid.setText("");
            tfuserid.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_tfuseridFocusGained

    private void tfuseridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfuseridFocusLost
        // TODO add your handling code here:
         if(tfuserid.getText().equals(""))
        {
            tfuserid.setText("Eg. Eid1");
            tfuserid.setForeground(new Color(153,153,153));
        }
            
    }//GEN-LAST:event_tfuseridFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(elogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(elogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(elogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(elogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new elogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactnumberlabelr;
    private javax.swing.JTextField fcontactnumber;
    private javax.swing.JPasswordField fpassword;
    private javax.swing.JPasswordField ftpassword;
    private javax.swing.JTextField fuserid;
    private javax.swing.JTextField fusername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel loginlabel;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JLabel passwordlabelr;
    private javax.swing.JButton registerbutton;
    private javax.swing.JLabel registerlabel;
    private javax.swing.JTextField tfaddress;
    private javax.swing.JTextField tfownerid;
    private javax.swing.JComboBox<String> tfrole;
    private javax.swing.JTextField tfsal;
    private javax.swing.JTextField tfuserid;
    private javax.swing.JTextField tfusername;
    private javax.swing.JLabel useridlabelr;
    private javax.swing.JLabel usernamelabel;
    private javax.swing.JLabel usernamelabelr;
    // End of variables declaration//GEN-END:variables

    private void userLogin(String userid, String username, String password) {
        System.out.println(userid);
        System.out.println(username);
        System.out.println(password);
        Connection dbconn = DBconnection.connectDB();
        try {
            PreparedStatement st;
            st = (PreparedStatement)dbconn.prepareStatement("Select * from employee where Eid = ? AND Name = ? AND Password = ?");
            st.setString(1,userid);
            st.setString(2,username);
            st.setString(3,password);
//            JOptionPane.showMessageDialog(this,"Login Successfull");           
        ResultSet res= st.executeQuery();
        if(res.next()){
            dispose();
            Ehome d=new Ehome();
            d.setTitle("Ehome");
            d.setVisible(true);      
//                display nest page
           }
        else{
            JOptionPane.showMessageDialog(this, "Fill Proper Detaails", "error", JOptionPane.ERROR_MESSAGE);
        }
        }catch (SQLException ex) {
            Logger.getLogger(Ologin.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }

    private void userRegister(String userid, String username, String contactnumber,String address, String role, String ownerid, String password, String sal) {
System.out.println(userid);
        System.out.println(username);
        System.out.println(password);
        Connection dbconn = DBconnection.connectDB();
        try {
            PreparedStatement st;
            st = (PreparedStatement)dbconn.prepareStatement("insert into employee (Eid,Name,Phno,Address,Role,Oid,Password,Salary) values(?,?,?,?,?,?,?,?)");   
            st.setString(1,userid);
            st.setString(2,username);
            st.setString(3,contactnumber);
            st.setString(4,address);
            st.setString(5,role);
            st.setString(6,ownerid);
            st.setString(7,password);
            st.setString(8,sal);
            JOptionPane.showMessageDialog(this,"Registration Successful");
            int res= st.executeUpdate();
            fuserid.setText("");
            fusername.setText("");
            fcontactnumber.setText("");
            tfaddress.setText("");
            tfsal.setText("");
            fpassword.setText("");
            tfownerid.setText("");
//            tfrole.setText("");
           
            tfuserid.requestFocus(); 
//            if(res.next()){
//                dispose();
//                Ohome d=new Ohome();
//                d.setTitle("Ohome");
//                d.setVisible(true);   
////                display nest page
//            }
        }catch (SQLException ex) {
                          JOptionPane.showMessageDialog(this, ex, "Error", JOptionPane.ERROR_MESSAGE);    

            Logger.getLogger(Ologin.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
   
}
