
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Diganth Rai
 */
public class Ologin extends javax.swing.JFrame {

    /**
     * Creates new form Ologin
     */
    public Ologin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        loginlabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tfuserid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        ftpassword = new javax.swing.JPasswordField();
        passwordlabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        loginbutton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Oregister = new javax.swing.JPanel();
        useridlabelr = new javax.swing.JLabel();
        usernamelabelr = new javax.swing.JLabel();
        contactnumberlabelr = new javax.swing.JLabel();
        addresslabelr = new javax.swing.JLabel();
        passwordlabelr = new javax.swing.JLabel();
        fuserid = new javax.swing.JTextField();
        fusername = new javax.swing.JTextField();
        fcontactnumber = new javax.swing.JTextField();
        faddress = new javax.swing.JTextField();
        registerbutton = new javax.swing.JButton();
        fpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        loginlabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        loginlabel.setText("LOGIN TO START!");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfuserid.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        tfuserid.setForeground(new java.awt.Color(153, 153, 153));
        tfuserid.setText("Eg. Oid1");
        tfuserid.setToolTipText("");
        tfuserid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfuseridFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfuseridFocusLost(evt);
            }
        });
        tfuserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuseridActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Userid");

        usernamelabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usernamelabel.setText("Username");

        tfusername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        passwordlabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordlabel.setText("Password");

        jPanel5.setBackground(new java.awt.Color(255, 204, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(15, 160));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(160, 15));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        loginbutton.setBackground(new java.awt.Color(255, 204, 0));
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(loginbutton)
                                        .addGap(75, 75, 75))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 58, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ftpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addGap(65, 65, 65))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                    .addComponent(usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)))
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfuserid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(81, 81, 81))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(loginlabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(loginlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfuserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamelabel)
                    .addComponent(tfusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordlabel)
                    .addComponent(ftpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(loginbutton)
                        .addGap(102, 102, 102)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 0));

        Oregister.setBackground(new java.awt.Color(255, 204, 0));

        useridlabelr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        useridlabelr.setText("User Id");

        usernamelabelr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usernamelabelr.setText("Username");

        contactnumberlabelr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        contactnumberlabelr.setText("Contact Number");

        addresslabelr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addresslabelr.setText("Address");

        passwordlabelr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordlabelr.setText("Password");

        fuserid.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        fuserid.setForeground(new java.awt.Color(153, 153, 153));
        fuserid.setText("Eg. Oid1");
        fuserid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fuseridFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fuseridFocusLost(evt);
            }
        });
        fuserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuseridActionPerformed(evt);
            }
        });

        fusername.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        fusername.setForeground(new java.awt.Color(153, 153, 153));
        fusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fusernameActionPerformed(evt);
            }
        });

        faddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faddressActionPerformed(evt);
            }
        });

        registerbutton.setBackground(new java.awt.Color(255, 255, 255));
        registerbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerbutton.setText("Submit");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });

        fpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpasswordActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("ARE YOU A NEW USER?...REGISTER NOW");

        javax.swing.GroupLayout OregisterLayout = new javax.swing.GroupLayout(Oregister);
        Oregister.setLayout(OregisterLayout);
        OregisterLayout.setHorizontalGroup(
            OregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OregisterLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OregisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OregisterLayout.createSequentialGroup()
                        .addGroup(OregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(useridlabelr, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernamelabelr)
                            .addComponent(contactnumberlabelr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addresslabelr, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordlabelr, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(OregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fuserid)
                            .addComponent(fusername)
                            .addComponent(fcontactnumber)
                            .addComponent(faddress)
                            .addComponent(fpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OregisterLayout.createSequentialGroup()
                        .addComponent(registerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        OregisterLayout.setVerticalGroup(
            OregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OregisterLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useridlabelr)
                    .addComponent(fuserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(OregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamelabelr)
                    .addComponent(fusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(OregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactnumberlabelr)
                    .addComponent(fcontactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(OregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addresslabelr)
                    .addComponent(faddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(OregisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordlabelr)
                    .addComponent(fpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(registerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(Oregister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Oregister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        home j=new home();
        j.show();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfuseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuseridActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        String userid=tfuserid.getText();
        String username=tfusername.getText();
        String password=String.valueOf(ftpassword.getPassword());
        if(userid.isEmpty() || username.isEmpty() || password.isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Username /Password should not be empty", "Error", JOptionPane.ERROR_MESSAGE);
        } else{
            userLogin(userid,username,password);
            //                    suserart the login process

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void fusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fusernameActionPerformed

    private void faddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faddressActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        // TODO add your handling code here:
        String userid=fuserid.getText();
        String username=fusername.getText();
        String contactnumber=fcontactnumber.getText();
        String address=faddress.getText();
        String password=String.valueOf(fpassword.getPassword());
// Regex field
        String useridregex="Oid[0-9]+";
        String passwordregex="^[A-Z][0-9 a-z]+[ @ # % & ! $ ]+$";
        String nameregex="^[A-Z][a-z]+";
        String phnregex="[0-9]+";
        
        
        if(userid.isEmpty() || username.isEmpty() || password.isEmpty() || contactnumber.isEmpty()|| address.isEmpty()  ) {
            JOptionPane.showMessageDialog(this, "Field is empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
//      Userid
        if(userid.length()<=5)
        {
            if(userid.matches(useridregex))
            {
                System.out.println("success1");
                //Username
                if(username.length()<=30)
                    {
                        if(username.matches(nameregex))
                        {
                            System.out.println("success2");
                             //contact number
                             if(contactnumber.length()==10)
                                    {
                                        if(contactnumber.matches(phnregex))
                                        {
                                            System.out.println("success3");
                                            //password

                                            if(password.length()==10){
                                                if(password.matches(passwordregex))
                                                {
                                                    userRegister(userid,username,contactnumber, address,password);
                                                }
                                                else
                                                {
                                                 JOptionPane.showMessageDialog(this, "Begin PASSWORD with Uppercase, use lowercase,,digits and end with (@,#,$,%,&,!)", "Error", JOptionPane.ERROR_MESSAGE);        
                                                }
                                            }

                                            else{
                                                  JOptionPane.showMessageDialog(this, "PASSWORD length is not 10 ", "Error", JOptionPane.ERROR_MESSAGE);
                                            }
                                            
                                        }
                                        else
                                        {
                                         JOptionPane.showMessageDialog(this, "Enter 10 digit CONTACT NUMBER", "Error", JOptionPane.ERROR_MESSAGE);        
                                        }
                                    }
                                    else
                                    {
                                         JOptionPane.showMessageDialog(this, "CONTACT NUMBER is not 10 ", "Error", JOptionPane.ERROR_MESSAGE);
                                    }    
                                }
                            else
                           {
                                JOptionPane.showMessageDialog(this, "Begin NAME with Uppercase followed by ONLY Lowercase", "Error", JOptionPane.ERROR_MESSAGE);        
                             }
                           }
                    else
                    {
                         JOptionPane.showMessageDialog(this, "Max NAME length is 30 ", "Error", JOptionPane.ERROR_MESSAGE);
                    }     
            }
            else
            {
             JOptionPane.showMessageDialog(this, "ID  not in the required form (eg.Oid1)", "Error", JOptionPane.ERROR_MESSAGE);        
            }
        }
        else
        {
             JOptionPane.showMessageDialog(this, "max ID length is 5 ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        

 
        
        
        
        


    }//GEN-LAST:event_registerbuttonActionPerformed

    private void fpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fpasswordActionPerformed

    private void fuseridFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fuseridFocusGained
        // TODO add your handling code here:
        if(fuserid.getText().equals("Eg. Oid1"))
        {
            fuserid.setText("");
            fuserid.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_fuseridFocusGained

    private void fuseridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fuseridFocusLost
        // TODO add your handling code here:
        if(fuserid.getText().equals(""))
        {
            fuserid.setText("Eg. Oid1");
            fuserid.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_fuseridFocusLost

    private void fuseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuseridActionPerformed

    private void tfuseridFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfuseridFocusGained
        // TODO add your handling code here:
        if(tfuserid.getText().equals("Eg. Oid1"))
        {
            tfuserid.setText("");
            tfuserid.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_tfuseridFocusGained

    private void tfuseridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfuseridFocusLost
        // TODO add your handling code here:
        if(tfuserid.getText().equals(""))
        {
            tfuserid.setText("Eg. Oid1");
            tfuserid.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_tfuseridFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ologin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ologin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ologin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ologin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ologin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Oregister;
    private javax.swing.JLabel addresslabelr;
    private javax.swing.JLabel contactnumberlabelr;
    private javax.swing.JTextField faddress;
    private javax.swing.JTextField fcontactnumber;
    private javax.swing.JPasswordField fpassword;
    private javax.swing.JPasswordField ftpassword;
    private javax.swing.JTextField fuserid;
    private javax.swing.JTextField fusername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel loginlabel;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JLabel passwordlabelr;
    private javax.swing.JButton registerbutton;
    private javax.swing.JTextField tfuserid;
    private javax.swing.JTextField tfusername;
    private javax.swing.JLabel useridlabelr;
    private javax.swing.JLabel usernamelabel;
    private javax.swing.JLabel usernamelabelr;
    // End of variables declaration//GEN-END:variables

    private void userLogin(String userid, String username, String password) {
         System.out.println(userid);
        System.out.println(username);
        System.out.println(password);
        Connection dbconn = DBconnection.connectDB();
        try {
            PreparedStatement st;
            st = (PreparedStatement)dbconn.prepareStatement("Select * from owner where Oid = ? AND Name = ? AND Password = ?");
            st.setString(1,userid);
            st.setString(2,username);
            st.setString(3,password);
//            JOptionPane.showMessageDialog(this,"Login Successfull");           
        ResultSet res= st.executeQuery();
        if(res.next()){
            dispose();
            Ohome d=new Ohome();
            d.setTitle("Ohome");
            d.setVisible(true);      
//                display nest page
           }
        else{
            JOptionPane.showMessageDialog(this, "Invalid credentials", "error", JOptionPane.ERROR_MESSAGE);
        }
        }catch (SQLException ex) {
            Logger.getLogger(Ologin.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
 
//    public class Validation {
// 
//    public List<String> validateLogin(String uname, String password) {
//        ArrayList<String> err = new ArrayList<String>();
//        if (uname.isEmpty()) {
//            err.add("User Name can not be empty");
//        } else if (uname.length() < 4) {
//            err.add("User Name is too short");
//        } else if (uname.length() > 20) {
//            err.add("user Name is too long");
//        }
//        if (password.isEmpty()) {
//            err.add("Password can not be empty");
//        } else if (password.length() < 4) {
//            err.add("Password is too short");
//        } else if (password.length() > 20) {
//            err.add("Password is too long");
//        }
//        return err;
//    }
//}

    private void userRegister(String userid, String username, String contactnumber, String address, String password) {
System.out.println(userid);
        System.out.println(username);
        System.out.println(password);
        Connection dbconn = DBconnection.connectDB();
        try {
            
            PreparedStatement st;
            st = (PreparedStatement)dbconn.prepareStatement("insert into owner (Oid,Name,Phno,Address,Password) values(?,?,?,?,?)");   
            st.setString(1,userid);
            st.setString(2,username);
            st.setString(3,contactnumber);
            st.setString(4,address);
            st.setString(5,password);
            JOptionPane.showMessageDialog(this,"Registration Successful");
            int res= st.executeUpdate();
            
            fuserid.setText("");
            fusername.setText("");
            fcontactnumber.setText("");
            faddress.setText("");
            fpassword.setText("");
            tfuserid.requestFocus();  
//            if(res.next()){
//                dispose();
//                Ohome d=new Ohome();
//                d.setTitle("Ohome");
//                d.setVisible(true);   
////                display nest page
//            }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex, "Error", JOptionPane.ERROR_MESSAGE);    
            Logger.getLogger(Ologin.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
   
}
